version: "3"
services:
  frontend:
    image: lewisjeong/docker-frontend
    volumes:
      - /app/node_modules # /app/node_modules는 docker container에 있는 파일들을 사용
      - ./frontend:/app # /app이 local에 있는 ./frontend에 있는 파일을 참조
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always # 서버가 꺼지면 항상 restart 한다.
    image: lewisjeong/docker-nginx
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend

  backend:
    image: lewisjeong/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: docker-fullstack-mysql.ciapofkwma9d.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: hongjun123
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
    mem_limit: 128m

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: johnahn
  #     MYSQL_DATABASE: myapp
  #   platform: linux/x86_64
